### ISSUE TITLE
[FEAT] 베이스라인 노트북 파일 추가

### ISSUE THREAD

**Issue by hwbae42** [boostcampaitech7/level2-recsys-movierecommendation-recsys-07-lv3#2]
## Background
- 실험을 위해 빠르게 작업해 볼 노트북 베이스라인이 필요합니다.

## Todo
- [x] train/valid split 구현
- [x] 모델 구현
- [x] loss 함수 구현
- [x] csv 파일 내보내기 구현
